#!/bin/bash

docker rm devsystemapiccom_nginx_1
docker rm devsystemapiccom_pile_1
docker rm devsystemapiccom_wu_1
docker rm devsystemapiccom_redislayers_1
docker rm devsystemapiccom_redisstats_1
docker rm devsystemapiccom_redistemp_1
docker rm devsystemapiccom_mongo_1
docker rm devsystemapiccom_postgis_1
