# dev.systemapic.com
wu:
  image: systemapic/wu
  links:
    - mongo
    - redislayers
    - redisstats
    - redistemp
    - redistokens
    - postgis
  ports: 
    - 3001
  environment:
    - SYSTEMAPIC_PRODMODE=false
    - SYSTEMAPIC_DOMAIN=dev.systemapic.com
  volumes_from:
    - store_data_devtemp
  volumes: 
    - /var/www/wu:/var/www/wu
  command: ./server.sh

pile: 
  image: systemapic/pile
  links: 
    - wu
    - mongo
    - redislayers
    - redisstats
    - redistokens
    - redistemp
    - postgis
  ports:
    - 3003
  volumes_from:
    - store_data_devtemp
  volumes:
    - /var/www/pile:/var/www/pile 
  command: ./pile-server.sh

nginx:
  image: systemapic/nginx
  links: 
    - pile
    - wu
  ports:
    - 443:443
    - 80:80

postgis:
  image: systemapic/postgis:latest
  ports:
    - 5432
  volumes_from:
    # - store_postgis_devtemp
    - store_postgis_devtemp_restored5
  environment:
    - PGVER=9.4
    - SYSTEMAPIC_RESTORE_POSTGIS_FROM=store_backup_devtemp
  command: ./start.sh

redislayers:
  image: systemapic/redis:layers
  ports: 
    - 6379
  volumes_from:
    - store_redis_devtemp

redisstats:
  image: systemapic/redis:stats
  ports: 
    - 6379
  volumes_from:
    - store_redis_stats_devtemp

redistemp:
  image: systemapic/redis:kue
  ports: 
    - 6379

redistokens:
  image: systemapic/redis:tokens
  ports: 
    - 6379
  volumes_from:
    - store_redis_tokens_devtemp

mongo: 
  image: systemapic/mongo:latest
  ports:
    - 27017
  volumes_from:
    - store_mongo_devtemp_5

backup: 
  image: systemapic/backup:postgis
  ports:
    - 5432
  links:
    - postgis
  volumes_from:
    - store_backup_devtemp
  environment:
    - SYSTEMAPIC_PRODMODE=false
