# systemapic / dev
#
# - whole systemapic dev setup
# - sharing /wu and /pile folders with localhost 
wu:
  image: systemapic/wu
  links:
    - redislayers
    - redisstats
    - redistemp
    - mongo
    - postgis
  ports: 
    - 3001
  volumes_from:
    - data_store_dev
  volumes: 
    - /var/www/wu:/var/www/wu
  command: ./server.sh

pile: 
  image: systemapic/pile
  links: 
    - redislayers
    - redisstats
    - redistemp
    - wu
    - mongo
    - postgis
  ports:
    - 3003
  volumes_from:
    - data_store_dev
  volumes:
    - /var/www/pile:/var/www/pile 
  command: ./pile-server.sh

postgis:
  image: systemapic/postgis
  ports:
    - 5432
  volumes_from:
    - postgis_store_dev
  command: ./start.sh

nginx:
  image: systemapic/nginx
  links: 
    - pile
    - wu
  ports:
    - 443:443
    - 80:80

redislayers:
  image: systemapic/redis:layers
  ports: 
    - 6379
  volumes_from:
    - redis_store_dev

redisstats:
  image: systemapic/redis:stats
  ports: 
    - 6379
  volumes_from:
    - redis_stats_store_dev

redistemp:
  image: systemapic/redis:kue
  ports: 
    - 6379

mongo: 
  image: systemapic/mongo
  ports:
    - 27017
  volumes_from:
    - mongo_store_dev 