# see domain-specific .yml for documentation
engine:
  # image: mapic/geo:latest 
  image: mapic/engine:latest 
  environment:
    MAPIC_DOMAIN: ${MAPIC_DOMAIN}
  working_dir: /mapic/modules/engine 
  expose:
    - "3001"
  volumes:
    - ${MAPIC_ROOT_FOLDER}/config/${MAPIC_DOMAIN}:/mapic/config
    - ${MAPIC_ROOT_FOLDER}/modules:/mapic/modules
  command: ./start-server.sh

mile: 
  # image: mapic/geo:latest
  image: mapic/mile:latest
  environment:
    MAPIC_DOMAIN: ${MAPIC_DOMAIN}
  working_dir: /mapic/modules/mile 
  expose:
    - "3003"
  volumes:
    - ${MAPIC_ROOT_FOLDER}/config/${MAPIC_DOMAIN}:/mapic/config
    - ${MAPIC_ROOT_FOLDER}/modules:/mapic/modules
  command: ./start-server.sh

nginx:
  image: mapic/nginx:latest
  volumes:
    - ${MAPIC_ROOT_FOLDER}/config/${MAPIC_DOMAIN}:/mapic/config

redis:
  image: redis:latest
  volumes:
    - ${MAPIC_ROOT_FOLDER}/config/${MAPIC_DOMAIN}:/mapic/config

mongo: 
  image: mapic/mongo:latest
  volumes:
    - ${MAPIC_ROOT_FOLDER}/config/${MAPIC_DOMAIN}:/mapic/config

postgis:
  image: mapic/postgis:latest
  volumes:
    - ${MAPIC_ROOT_FOLDER}/config/${MAPIC_DOMAIN}:/mapic/config
