# systemapic / dev
#
# - whole systemapic dev setup
# - sharing /wu and /pile folders with localhost 
wu:
  image: systemapic/wu
  links:
    - mongo
    - redislayers
    - redisstats
    - redistemp
    - postgis
  ports: 
    - 3001
  environment:
    - SYSTEMAPIC_PRODMODE=false
  volumes_from:
    - data_store_dev2
  volumes: 
    - /var/www/wu:/var/www/wu
  command: ./server.sh

pile: 
  image: systemapic/pile
  links: 
    - wu
    - mongo
    - redislayers
    - redisstats
    - redistemp
    - postgis
  ports:
    - 3003
  volumes_from:
    - data_store_dev2  
  volumes:
    - /var/www/pile:/var/www/pile 
  command: ./pile-server.sh

nginx:
  image: systemapic/nginx
  links: 
    - pile
    - wu
  ports:
    - 443:443
    - 80:80

postgis:
  # image: systemapic/postgis
  image: systemapic/postgis:all_logs
  ports:
    - 5432
  volumes_from:
    #- postgis_store_dev2
    - testme_pgdata_store2
  command: ./start.sh

redislayers:
  image: systemapic/redis:layers
  ports: 
    - 6379
  volumes_from:
    - redis_store_dev2

redisstats:
  image: systemapic/redis:stats
  ports: 
    - 6379
  volumes_from:
    - redis_stats_store_dev2

redistemp:
  image: systemapic/redis:kue
  ports: 
    - 6379

mongo: 
  image: systemapic/mongo
  ports:
    - 27017
  volumes_from:
    - mongo_store_dev2

backup: 
  image: systemapic/backup:postgis
  ports:
    - 5432
  links:
    - postgis
  volumes_from:
    - postgis_backup_store
