#!/bin/bash

docker rm dev3systemapiccom_nginx_1
docker rm dev3systemapiccom_pile_1
docker rm dev3systemapiccom_wu_1
docker rm dev3systemapiccom_redislayers_1
docker rm dev3systemapiccom_redisstats_1
docker rm dev3systemapiccom_redistemp_1
docker rm dev3systemapiccom_mongo_1
docker rm dev3systemapiccom_postgis_1
