# dev.systemapic.com
wu:
  image: systemapic/wu
  links:
    - mongo
    - redislayers
    - redisstats
    - redistemp
    - redistokens
    - postgis
  environment:
    - SYSTEMAPIC_PRODMODE=false
    - SYSTEMAPIC_DOMAIN=dev.systemapic.com
  volumes_from:
    - data_store_dev_common
  volumes: 
    - /var/www/wu:/var/www/wu
  command: ./server.sh

pile: 
  image: systemapic/pile
  links: 
    - wu
    - mongo
    - redislayers
    - redisstats
    - redistokens
    - redistemp
    - postgis
  volumes_from:
    - data_store_dev_common
  volumes:
    - /var/www/pile:/var/www/pile 
  command: ./pile-server.sh

nginx:
  image: systemapic/nginx
  links: 
    - pile
    - wu
  ports:
    - 443:443
    - 80:80

postgis:
  image: systemapic/postgis
  volumes_from:
    - postgis_store_dev
  command: ./start.sh

redislayers:
  image: systemapic/redis:layers
  volumes_from:
    - redis_store_dev

redisstats:
  image: systemapic/redis:stats
  volumes_from:
    - redis_stats_store_dev

redistemp:
  image: systemapic/redis:kue

redistokens:
  image: systemapic/redis:tokens
  volumes_from:
    - store_dev_redis_tokens

mongo: 
  image: systemapic/mongo:latest
  volumes_from:
    - mongo_store_dev

# backup: 
#   image: systemapic/backup:postgis
#   links:
#     - postgis
#   volumes_from:
#     - postgis_backup_store
#   environment:
#     - SYSTEMAPIC_PRODMODE=false
