#!/bin/bash

docker rm betasystemapiccom_nginx_1
docker rm betasystemapiccom_pile_1
docker rm betasystemapiccom_wu_1
docker rm betasystemapiccom_redislayers_1
docker rm betasystemapiccom_redisstats_1
docker rm betasystemapiccom_redistemp_1
docker rm betasystemapiccom_mongo_1
docker rm betasystemapiccom_postgis_1
