#!/bin/bash

docker rm dev2systemapiccom_nginx_1
docker rm dev2systemapiccom_pile_1
docker rm dev2systemapiccom_wu_1
docker rm dev2systemapiccom_redislayers_1
docker rm dev2systemapiccom_redisstats_1
docker rm dev2systemapiccom_redistemp_1
docker rm dev2systemapiccom_mongo_1
docker rm dev2systemapiccom_postgis_1
docker rm dev2systemapiccom_backup_1
